package com.mycompany.ehealthcare_portal;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Vishma
 */
public class MainFrame extends javax.swing.JFrame {
    String patient_name;
    String name;
    String password;
    String confpass;
    String health;
    String pnum;

    public MainFrame() {
        initComponents();
    }
    
    void moveToLogin() {
        Login a=new Login();
        a.setVisible(true);
        this.dispose();
    }
    
    Boolean updateData() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/patientdata?useSSL=false","root","root");
            String sql="Insert into patientdata values('"+name+"', '"+patient_name+"', '"+pnum+"', '"+health+"', '"+password+"')";
            Statement stm=con.createStatement();
            stm.execute(sql);
            JOptionPane.showMessageDialog(this, "Registered");
            return true;
 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            return false;
        }
    }
    
    Boolean verification() {
        patient_name=pname.getText();
        name=uname.getText();
        password=pass.getText();
        confpass=cpass.getText();
        pnum=pnumber.getText();
        
        // Verification
        if ("".equals(patient_name)){
            JOptionPane.showMessageDialog(this, "Please enter name correctly:");
            return false;
        } else if ("".equals(name)) {
            JOptionPane.showMessageDialog(this, "Please enter username correctly:");
            return false;
        } else if ("".equals(password)){
            JOptionPane.showMessageDialog(this, "Please enter password correctly:");
            return false;
        } else if ("".equals(confpass)){
            JOptionPane.showMessageDialog(this, "Please confirm password:");
            return false;
        } else if ("".equals(pnum)){
            JOptionPane.showMessageDialog(this, "Please enter phone number correctly:");
            return false;
        } else if (passwordCheck()) {
            JOptionPane.showMessageDialog(this, "Correct data entered. Continue");
            return true;
        }
        if (!numberCheck()){
            return false;
        }
        return false;
    }
    
    Boolean numberCheck() {
        String phone=pnumber.getText();
        if (phone.length()!=10){
            phoneNumberError.setText("Phone number must be 10 digits");
            return false;
        }
        return true;
    }
    
    Boolean passwordCheck() {
        // empty check
        String password=pass.getText();
        String cpassword=cpass.getText();
        if (password.equals("") && cpassword.equals("")) {
            JOptionPane.showMessageDialog(this,"Password field cannot be empty!");
            return false;
        }
        if (password.length()<8){
            JOptionPane.showMessageDialog(this,"Please create password greater than 8 digits");
            return false;
        }
        if (!password.equals(cpassword)) {
            phoneNumberError.setText("Passwords do not match");
            return false;
        } else {
            phoneNumberError.setText("");
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        pnumber = new javax.swing.JTextField();
        signupbtn = new javax.swing.JButton();
        cpass = new javax.swing.JPasswordField();
        pass = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        phoneNumberError = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        errorMessage1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Patient name:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 130, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Username:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 130, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Phone number:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 130, 40));

        pname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnameActionPerformed(evt);
            }
        });
        getContentPane().add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 110, 30));

        pnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnumberActionPerformed(evt);
            }
        });
        getContentPane().add(pnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 110, 30));

        signupbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        signupbtn.setForeground(new java.awt.Color(0, 204, 0));
        signupbtn.setText("Signup");
        signupbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbtnActionPerformed(evt);
            }
        });
        getContentPane().add(signupbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));

        cpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpassActionPerformed(evt);
            }
        });
        getContentPane().add(cpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 100, 23));

        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 100, 23));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Password:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 130, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Confirm Password:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 130, 40));

        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        getContentPane().add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 110, 30));

        phoneNumberError.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(phoneNumberError, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 270, 20));

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("User signup");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 50));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("Signup:");
        jPanel3.add(jLabel2);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 870, 40));

        errorMessage1.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(errorMessage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 270, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnameActionPerformed

    private void pnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnumberActionPerformed

    private void signupbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbtnActionPerformed
        if(verification()){
            if(updateData()){
                JOptionPane.showMessageDialog(this,"User registered. Now log in:");
                moveToLogin();
            };
        };
    }//GEN-LAST:event_signupbtnActionPerformed

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void cpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpassActionPerformed
        
    }//GEN-LAST:event_cpassActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        
    }//GEN-LAST:event_passActionPerformed
    
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cpass;
    private javax.swing.JLabel errorMessage1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel phoneNumberError;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField pnumber;
    private javax.swing.JButton signupbtn;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
